version: '3.1'

services:

  input_db:
    container_name: input_db
    image: synthesizedio/pagila
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 6000:5432
    healthcheck:
      test: "pg_isready -d postgres -q -U ${POSTGRES_USER:-postgres}"
      interval: "1s"
      timeout: "1s"
      retries: 30


  output_db:
    container_name: output_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 6001:5432
    healthcheck:
      test: "pg_isready -d postgres -q -U ${POSTGRES_USER:-postgres}"
      interval: "1s"
      timeout: "1s"
      retries: 30


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8888:80"
