version: '3.1'

services:

  input_db:
    container_name: input_db
    image: synthesizedio/pagila
    environment:
      POSTGRES_PASSWORD: postgres
    ports: [ "6000:5432" ]


  output_db:
    container_name: output_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports: [ "6001:5432" ]


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


  databases:
    container_name: databases
    image: docker/whalesay
    command: >
      cowsay
        "Both the source and target databases have been started on
         port 6000 and 6001 respectively, and are ready for TDK exercises!
         To check it out with pgAdmin, simply go to this link:
         http://localhost:8888 and use 'postgres' as the password."
    # depends_on:
    #   input_db:
    #     condition: service_healthy
    #   output_db:
    #     condition: service_healthy
    #   pgadmin:
    #     condition: service_started
